### ISSUE TITLE
Getting random craches 

### ISSUE THREAD

**Issue by mathiastornblom** [martijnpoppen/homey-betterstack#1]
Using the package it sometimes throws this;
Error: ENOENT: no such file or directory, uv_resident_set_memory
    at process.memoryUsage (node:internal/process/per_thread:168:5)
    at RejectionHandler.getProcessInfo (/app/node_modules/winston/lib/winston/rejection-handler.js:112:28)
    at RejectionHandler.getAllInfo (/app/node_modules/winston/lib/winston/rejection-handler.js:93:21)
    at RejectionHandler._unhandledRejection (/app/node_modules/winston/lib/winston/rejection-handler.js:168:23)
    at process.emit (node:events:529:35)
    at process.emit (node:domain:489:12)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
    
    There seams to be a dependency to winston 3.12.0 or higher and I cas see that I have the latest 3.14.2. could there be a compatibility issue?

**Comment by martijnpoppen** [comment]
Hi @mathiastornblom 
I experienced this myself aswell! I'm looking into it, unfortunately i didn't find a solution yet.
It seems to be related to the way Homey works.
I'll leave this issue open and will update you once i find something.
